spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authdb
    username: myuser
    password: mypassword
  security:
    jwt:
      secret: my-super-secret-key
      expiration: 3600000  # 1 hour

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka