spring:
  application:
    name: USER-PROFILE-SERVICE

  data:
    mongodb:
      uri: mongodb+srv://universe123:zadian123@cluster0.irfp6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userprofile

  flyway:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082