server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false        # Eureka Server should NOT register itself
    fetch-registry: false              # Eureka Server should not fetch registry (standalone)
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # URL for services to register with Eureka

management:
  endpoints:
    web:
      exposure:
        include: ["*"]  # Expose all management endpoints (this includes Prometheus)
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

spring:
  application:
    name: eureka-server
